version: "3.7"

services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - "./postgtesdb/Sql:/docker-entrypoint-initdb.d"
