version : '3'
services:
    mysql:
        image: mysql:5.7
        volumes:
            - mysql-volume:/var/lib/mysql
        ports:
        - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "password"
volumes:
    mysql-volume:
        external: true
